#!/usr/bin/env bash

set -euxo pipefail

# install homebrew
if ! command -v brew; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# check homebrew
brew --version

# install junkcoin
if ! command -v junkcoind; then
  brew install junkcoin
fi

# check junkcoind
junkcoind --version

# write config
if [[ ! -f ~/Library/Application\ Support/Junkcoin/junkcoin.conf ]]; then
  printf 'txindex=1\nsignet=1\n' > ~/Library/Application\ Support/Junkcoin/junkcoin.conf
fi

# start junkcoind
if ! junkcoin-cli getblockchaininfo; then
  brew services start junkcoin
fi

# check junkcoind
junkcoin-cli getblockchaininfo | grep signet

# install ord
if ! command -v ord; then
  curl --proto '=https' --tlsv1.2 -fsLS https://raw.githubusercontent.com/apezord/ord-junkcoin/master/install.sh?token=GHSAT0AAAAAAB657S54D565E7TB4B3NBCE4Y736PRQ | bash -s
fi

# check ord
ord --version
